### ISSUE TITLE
Uncaught exception on app start on Mac

### ISSUE THREAD

**Issue by lavabyrd** [soundshed/soundshed-app#3]
Currently repro'd on Big Sur and Mojave. Starting the app causes an uncaught exception which i believe may be linked to https://github.com/electron/electron/issues/7476. 

I'll do a bit of reading on it over the weekend and see if a fix is possible or if we'd need a mac developer account. 

I'll let you know what I find out

Error:

```
Uncaught Exception:
Error: Could not get code signature for running application
at initUpdater (/private/var/folders/xr/jj7wzy0x009fy61mddb1gr540000gn/T/AppTranslocation/4650D714-C061-470A-947F-120356450B95/d/soundshed.app/Contents/Resources/app/node_modules/update-electron-app/index.js:54:15)
at App.<anonymous> (/private/var/folders/xr/jj7wzy0x009fy61mddb1gr540000gn/T/AppTranslocation/4650D714-C061-470A-947F-120356450B95/d/soundshed.app/Contents/Resources/app/node_modules/update-electron-app/index.js:33:43)
at App.emit (events.js:315:20)
```

**Comment by webprofusion-chrisc** [comment]
Thanks, I've got the dev account I just need to look into it enough to sort out the app signing. There is some argument for distributing the app via the official map app store so that updates might be a bit more dependable and install would be easier for end users.

**Comment by webprofusion-chrisc** [comment]
This should be resolved on macOS now with latest updates.

**Comment by lavabyrd** [comment]
Just installed 1.0.19 fresh (fully removed 1.0.18 as it was hanging on the update) and still getting an uncaught exception on startup:

```
Uncaught Exception:
Error: Could not get code signature for running application
at initUpdater (/Applications/Soundshed.app/Contents/Resources/app/node_modules/update-electron-app/index.js:54:15)
at App.<anonymous> (/Applications/Soundshed.app/Contents/Resources/app/node_modules/update-electron-app/index.js:33:43)
at App.emit (events.js:315:20)
```

Is there a flag we can use to run this in a debug mode and perhaps dump out more meaningful logs for you?

**Comment by webprofusion-chrisc** [comment]
Thanks, just reporting it as still a problem is helpful enough :) - I'd solved the issue in my manual build but the automated build in GitHub is still having issues.

**Comment by webprofusion-chrisc** [comment]
Signed macOS version now solved in 1.0.20.

**Comment by lavabyrd** [comment]
Yup, confirmed all good here! I'll close it out!
